[workspace]

members = [
    "algebra",
    "bench-utils",
    "primitives",
    "proof-systems",
    "r1cs/core",
    "r1cs/gadgets/std",
    "r1cs/gadgets/crypto",
]

[profile.release]
lto = "thin"
opt-level = 3
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 3
lto = "thin"
incremental = true
debug-assertions = true
debug = true
